# Generated by Django 5.0.4 on 2024-05-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Active'), ('B', 'Blocked'), ('D', 'Deleted')], default='R', max_length=1),
        ),
    ]
