# Generated by Django 5.0.4 on 2024-05-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='user_status',
        ),
    ]
