# Generated by Django 5.0.4 on 2024-07-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
