# Generated by Django 5.0.4 on 2024-08-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_identity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
