version: '3.9'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 jelly_backend.wsgi:application
    volumes:
      - .:/app
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - jelly_network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - jelly_network

  celery:
    build: .
    command: celery -A jelly_backend worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    env_file:
      - .env
    networks:
      - jelly_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/nginx/certs:ro
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - web
    networks:
      - jelly_network

networks:
  jelly_network:
    driver: bridge
