version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - jelly_network_dev

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - jelly_network_dev

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - jelly_network_dev

  celery:
    build: .
    command: celery -A jelly_backend worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    env_file:
      - .env
    networks:
      - jelly_network_dev

networks:
  jelly_network_dev:
    driver: bridge
