version: '3.9'

services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --access-logfile - --error-logfile - jelly_backend.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    networks:
      - jelly_network
    depends_on:
      - redis
      - rabbitmq

  celery:
    build: .
    command: celery -A jelly_backend worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - rabbitmq
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    env_file:
      - .env
    networks:
      - jelly_network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - jelly_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - jelly_network

networks:
  jelly_network:
    driver: bridge
