version: '3.9'

services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --access-logfile - --error-logfile - jelly_backend.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    networks:
      - jelly_network

  celery:
    build: .
    command: celery -A jelly_backend worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    env_file:
      - .env
    networks:
      - jelly_network

networks:
  jelly_network:
    driver: bridge
