OUATH_TAG = ['OAuth']
JWT_TAG = ['JWT']
USER_TAG = ['User']
ACCOUNT_ACTIVATION_TOKEN_TAG = ['Account Activation Token']
PASSWORD_RESET_TOKEN_TAG = ['Password Reset Token']
PRODUCTS_TAG = ['Products']
