# Generated by Django 5.0.4 on 2024-07-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
