# Generated by Django 5.0.4 on 2024-08-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
